### ISSUE TITLE
Travis build is failing because 3 values in mkdocs.yml are not recognized

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-iscape-docs#1]
3 values in `mkdocs.yml` are not recognized

```
WARNING -  Config value: 'hidden'. Warning: Unrecognised configuration name: hidden 
WARNING -  Config value: 'index_page'. Warning: Unrecognised configuration name: index_page 
WARNING -  Config value: 'footer'. Warning: Unrecognised configuration name: footer 
```

2 solutions :
- A: fix the 3 warnings.
- B: Remove the `--strict` from `mkdocs build --verbose --clean --strict` inside `.travis.yml`

What do you think @pral2a ?

**Comment by pral2a** [comment]
Yes, I have the same issue on local but everything works fine. It was introduced by one of the extentions. 

I will go for B

Thanks
